Repository kubevirt/machine-remediation, pull requests merged in 2019-08, with the labels that each got.

#26 Create CRDS via operator
  Makefile
  cmd/machine-remediation-operator/BUILD.bazel
  cmd/machine-remediation-operator/main.go
  go.mod
  manifests/BUILD.bazel
  manifests/generated/machine-remediation-operator-csv.yaml.in
  manifests/generated/machine-remediation-operator.yaml.in
  manifests/release/machine-remediation-operator.yaml.in
  pkg/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/operator/BUILD.bazel
  pkg/operator/components/components.go
  pkg/operator/components/rbac.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/resources.go
  tools/manifest-templator/manifest-templator.go
  vendor/modules.txt
Labels: size/XL

#27 Move CSV generator to separate binary and add it under operator container
  Makefile
  cmd/machine-remediation-operator/BUILD.bazel
  hack/generate/csv.sh
  hack/generate/templates.sh
  manifests/generated/machine-remediation-operator-csv.yaml.in
  pkg/operator/components/csv.go
  tools/csv-generator/BUILD.bazel
  tools/csv-generator/csv-generator.go
  tools/resource-generator/resource-generator.go
Labels: size/L

#30 Add option to dump operator CRD together with CSV
  hack/generate/crds.sh
  tools/csv-generator/BUILD.bazel
  tools/csv-generator/csv-generator.go
Labels: size/S

#32 Do not skip remediation when the machine does not have machineset
  pkg/controllers/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/controllers/machineremediation/BUILD.bazel
  pkg/controllers/machineremediation/machineremediation_controller.go
Labels: size/S

#33 Add events permissions for all controllers
  pkg/operator/components/rbac.go
Labels: size/S

#34 Remove tag field from MRO CRD
  manifests/generated/machine-remediation-operator-csv.yaml.in
  pkg/operator/components/csv.go
Labels: size/S

#28 Add support for node annotation to disable node fencing
  pkg/controllers/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: size/M

#35 Fix machine remediation controller
  cmd/machine-remediation/main.go
  pkg/baremetal/remediator/remediator.go
  pkg/controllers/machinedisruptionbudget/BUILD.bazel
  pkg/controllers/machinedisruptionbudget/machinedisruptionbudget_controller.go
  pkg/controllers/machinedisruptionbudget/machinedisruptionbudget_controller_test.go
  pkg/controllers/machinehealthcheck/BUILD.bazel
  pkg/controllers/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/controllers/machineremediation/BUILD.bazel
  pkg/controllers/machineremediation/machineremediation_controller.go
  pkg/operator/components/rbac.go
  pkg/operator/operator.go
Labels: size/L

#36 Get image repository from the operator if it does not exist
  pkg/operator/operator.go
  pkg/operator/resources.go
Labels: size/M

#37 Merge pull request #36 from cynepco3hahue/get_image_repository_from_operator
  pkg/operator/operator.go
  pkg/operator/resources.go
Labels: size/M

#38 Use conditions status from core package
  pkg/apis/machineremediation/v1alpha1/machineremediationoperator_types.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
Labels: size/M

#39 Merge pull request #38 from cynepco3hahue/change_condition_type
  pkg/apis/machineremediation/v1alpha1/machineremediationoperator_types.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
Labels: size/M

#40 Use soft affinity during deployment scheduling
  manifests/generated/machine-remediation-operator-csv.yaml.in
  manifests/generated/machine-remediation-operator.yaml.in
  pkg/operator/components/deployments.go
Labels: size/M

#41 Merge pull request #40 from cynepco3hahue/use_soft_affinity
  manifests/generated/machine-remediation-operator-csv.yaml.in
  manifests/generated/machine-remediation-operator.yaml.in
  pkg/operator/components/deployments.go
Labels: size/M

#42 Push release images
  .travis.yml
Labels: size/XS

#43 Merge pull request #42 from cynepco3hahue/build_release_containers
  .travis.yml
Labels: size/XS

#47 Bug 1704587: Reconcile nodes on MHC changes
  pkg/controllers/machinehealthcheck/BUILD.bazel
  pkg/controllers/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/utils/testing/testing.go
Labels: size/L

#50 Create informers for openshift-machine-api namespace under the operator
  cmd/machine-remediation-operator/BUILD.bazel
  cmd/machine-remediation-operator/main.go
Labels: size/S

#54 Add informer for None namespace
  cmd/machine-remediation-operator/BUILD.bazel
  cmd/machine-remediation-operator/main.go
Labels: size/XS

#56 Adds a Go file to project root, for "dep" dependency manager
  BUILD
  doc.go
Labels: size/M

#60 Create OWNERS
  OWNERS
Labels: size/XS

#62 Use 'Replica: 1' on clusters with a single master
  pkg/apis/machineremediation/v1alpha1/BUILD.bazel
  pkg/apis/machineremediation/v1alpha1/replicas.go
  pkg/operator/operator_test.go
  pkg/operator/resources.go
Labels: size/M
