Repository kubevirt/machine-remediation, pull requests merged in 2019-09, with the labels that each got.

#64 Move getReplicasCount method from the apis package
  pkg/apis/machineremediation/v1alpha1/BUILD.bazel
  pkg/apis/machineremediation/v1alpha1/replicas.go
  pkg/consts/consts.go
  pkg/operator/components/csv.go
  pkg/operator/operator_test.go
  pkg/operator/resources.go
Labels: size/M

#67 Add get, list and watch nodes permissions to MRO
  pkg/operator/components/rbac.go
Labels: size/S

#71 Add remediation strategy documentation
  docs/machine-health-check.md
  pkg/apis/machineremediation/v1alpha1/machinehealthcheck_types.go
Labels: size/M

#46 Add Status section to MachineHealthCheck object
  manifests/generated/crds/machineremediation_v1alpha1_machinehealthcheck.yaml
  pkg/apis/machineremediation/v1alpha1/machinehealthcheck_types.go
  pkg/apis/machineremediation/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/machinedisruptionbudget/BUILD.bazel
  pkg/controllers/machinedisruptionbudget/machinedisruptionbudget_controller.go
  pkg/controllers/machinehealthcheck/BUILD.bazel
  pkg/controllers/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/operator/components/rbac.go
  pkg/utils/conditions/BUILD.bazel
  pkg/utils/conditions/conditions.go
  pkg/utils/conditions/conditions_test.go
  pkg/utils/machines/BUILD.bazel
  pkg/utils/machines/machines.go
  pkg/utils/machines/machines_test.go
  pkg/utils/testing/testing.go
Labels: approved, lgtm, size/XXL

#73 Use KubeVirtCI providers for local development
  .gitignore
  .travis.yml
  Makefile
  cluster-up/cli.sh
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/okd-4.1/README.md
  cluster-up/cluster/okd-4.1/provider.sh
  cluster-up/down.sh
  cluster-up/hack/common.key
  cluster-up/hack/common.sh
  cluster-up/hack/config-default.sh
  cluster-up/hack/config.sh
  cluster-up/kubeconfig.sh
  cluster-up/kubectl.sh
  cluster-up/oc.sh
  cluster-up/ssh.sh
  cluster-up/up.sh
  cluster-up/virtctl.sh
  hack/cluster/build.sh
  hack/cluster/clean.sh
  hack/cluster/deploy.sh
  hack/config-default.sh
  hack/config.sh
  hack/kubevirtci/download.sh
  hack/kubevirtci/sha.txt
  hack/kubevirtci/version.txt
Labels: size/XL

#29 disable fencing feature doc
  docs/disable-fencing.txt
Labels: size/M

#74 Deploy master mhc mdb
  cmd/machine-remediation-operator/BUILD.bazel
  cmd/machine-remediation-operator/main.go
  go.mod
  go.sum
  manifests/generated/machine-remediation-operator-csv.yaml.in
  manifests/generated/machine-remediation-operator.yaml.in
  pkg/apis/machineremediation/v1alpha1/machinehealthcheck_types.go
  pkg/consts/consts.go
  pkg/operator/BUILD.bazel
  pkg/operator/components/BUILD.bazel
  pkg/operator/components/mdb.go
  pkg/operator/components/mhc.go
  pkg/operator/components/rbac.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/resources.go
  pkg/utils/mapper/BUILD.bazel
  pkg/utils/mapper/mapper.go
  pkg/utils/testing/BUILD.bazel
  pkg/utils/testing/testing.go
  vendor/github.com/openshift/api/LICENSE
  vendor/github.com/openshift/api/config/v1/BUILD.bazel
  vendor/github.com/openshift/api/config/v1/doc.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/stringsource.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: size/XXL

#75 Merge pull request #74 from cynepco3hahue/deploy_master_mhc_mdb
  cmd/machine-remediation-operator/BUILD.bazel
  cmd/machine-remediation-operator/main.go
  go.mod
  go.sum
  manifests/generated/machine-remediation-operator-csv.yaml.in
  manifests/generated/machine-remediation-operator.yaml.in
  pkg/apis/machineremediation/v1alpha1/machinehealthcheck_types.go
  pkg/consts/consts.go
  pkg/operator/BUILD.bazel
  pkg/operator/components/BUILD.bazel
  pkg/operator/components/mdb.go
  pkg/operator/components/mhc.go
  pkg/operator/components/rbac.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/resources.go
  pkg/utils/mapper/BUILD.bazel
  pkg/utils/mapper/mapper.go
  pkg/utils/testing/BUILD.bazel
  pkg/utils/testing/testing.go
  vendor/github.com/openshift/api/LICENSE
  vendor/github.com/openshift/api/config/v1/BUILD.bazel
  vendor/github.com/openshift/api/config/v1/doc.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/stringsource.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: size/XXL

#78 Update only the status of the MDB under the MHC
  pkg/controllers/machinedisruptionbudget/machinedisruptionbudget_controller.go
Labels: size/XS

#80 Use machine master role label on masters MHC and MDB resources
  pkg/consts/consts.go
  pkg/operator/components/mdb.go
  pkg/operator/components/mhc.go
  pkg/operator/resources.go
Labels: size/S

#82 chore(dep): remove version from deploy immutables
  manifests/generated/machine-remediation-operator-csv.yaml.in
  manifests/generated/machine-remediation-operator.yaml.in
  pkg/operator/components/deployments.go
Labels: lgtm, size/S

#84 Set reboot annotation on the bare metal host
  pkg/baremetal/remediator/BUILD.bazel
  pkg/baremetal/remediator/remediator.go
  pkg/baremetal/remediator/remediator_test.go
  pkg/consts/consts.go
Labels: size/L

#86 Does not update default MHC and MDB resources on the reconcile
  pkg/operator/operator.go
  pkg/operator/resources.go
Labels: size/S

#89 Add list and watch node permissions to the MDB service account
  pkg/operator/components/rbac.go
Labels: dco-signoff: yes, size/XS

#88 Pass controllers images as ENV variables under the operator
  Makefile
  cluster-up/cluster/okd-4.1/provider.sh
  hack/cluster/build.sh
  hack/config-default.sh
  hack/generate/csv.sh
  hack/generate/manifests.sh
  hack/generate/templates.sh
  hack/kubevirtci/sha.txt
  hack/kubevirtci/version.txt
  manifests/generated/crds/machineremediation_v1alpha1_machineremediationoperator.yaml
  manifests/generated/machine-remediation-operator-cr.yaml.in
  manifests/generated/machine-remediation-operator-csv.yaml.in
  manifests/generated/machine-remediation-operator.yaml.in
  pkg/apis/machineremediation/v1alpha1/machineremediationoperator_types.go
  pkg/consts/consts.go
  pkg/operator/BUILD.bazel
  pkg/operator/components/csv.go
  pkg/operator/components/deployments.go
  pkg/operator/components/mro.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/resources.go
  tools/csv-generator/csv-generator.go
  tools/manifest-templator/manifest-templator.go
  tools/resource-generator/resource-generator.go
  tools/utils/marshaller_test.go
Labels: dco-signoff: yes, size/L
