Repository kubevirt/machine-remediation, pull requests merged in 2019-10, with the labels that each got.

#91 Add vim temporary files to .gitignore
  .gitignore
Labels: dco-signoff: yes, lgtm, size/XS

#90 Add events to MHC controller
  pkg/controllers/machinehealthcheck/BUILD.bazel
  pkg/controllers/machinehealthcheck/machinehealthcheck_controller.go
  pkg/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: dco-signoff: yes, size/L

#93 Add events to baremetal remediator
  pkg/baremetal/remediator/BUILD.bazel
  pkg/baremetal/remediator/remediator.go
  pkg/baremetal/remediator/remediator_test.go
  pkg/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/utils/testing/testing.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#95 Do not push MHC and MDB images
  BUILD
  hack/config-default.sh
Labels: dco-signoff: yes, size/XS

#98 Update README
  .travis.yml
  Makefile
  README.md
Labels: dco-signoff: yes, size/S

#99 Update github token under travis
  .travis.yml
Labels: dco-signoff: yes
